FROM python:3.9

WORKDIR /app

# Instalar dependencias
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copiar los scripts de entrenamiento y los datos
COPY . .

CMD ["python", "train.py"]
