FROM python:3.9

WORKDIR /app

# Instalar dependencias
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copiar los scripts de preprocesamiento
COPY . .

#CMD ["python", "load_penguins.py"]
