FROM python:3.9

WORKDIR /app

# Instalar dependencias
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copiar los archivos de la API
COPY . .

RUN ls

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
